### ISSUE TITLE
Copy number classes error?

### ISSUE THREAD

**Issue by Fponelle** [bioinf-jku/panelcn.mops#21]
Hi,

I'm using panelcn.mops with default values of expected fold changes of the copy number classes: c(0.025, 0.57, 1, 1.46, 2)
But I have a lot of targets annotated CN0 while the log(RC ratio: RC.norm/medRC.norm) is clearly not under 0.025.

Please find below a sample of examples:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>

<body>

  | Sample | Chr | Gene | Exon | Start | End | RC | medRC | RC.norm | medRC.norm | lowQual | CN | RC.norm/medRC.norm
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
36 | 1509L0065-A_S10.recal.bam | chr1 | CHD5_ex08 | CHD5_ex08 | 6209285 | 6209522 | 4167 | 4942.5 | 42070 | 46431 |   | CN0 | 0,906075682195085
44 | 1509L0065-A_S10.recal.bam | chr1 | CDH5_UTR5 | CDH5_UTR5 | 6240083 | 6240381 | 6290 | 6133.5 | 63504 | 55952 |   | CN0 | 1,13497283385759
126 | 1509L0065-A_S10.recal.bam | chr1 | CDC73_UTR5 | CDC73_UTR5 | 193091087 | 193091330 | 5588 | 5618.5 | 61545 | 56091 |   | CN0 | 1,09723485051078
133 | 1509L0065-A_S10.recal.bam | chr1 | CDC73_ex07 | CDC73_ex07 | 193110929 | 193111216 | 4367 | 4764 | 44089 | 49890 |   | CN0 | 0,883724193225095
134 | 1509L0065-A_S10.recal.bam | chr1 | CDC73_ex08 | CDC73_ex08 | 193116946 | 193117115 | 3177 | 3550 | 32075 | 37137 |   | CN0 | 0,863693890190376
176 | 1509L0065-A_S10.recal.bam | chr2 | MSH2_ex14 | MSH2_ex14 | 47705360 | 47705678 | 5702 | 6707.5 | 52334 | 57824 |   | CN0 | 0,905056723851688
198 | 1509L0065-A_S10.recal.bam | chr2 | BCL2L11_UTR5_ex01 | BCL2L11_UTR5_ex01 | 111878490 | 111878765 | 3831 | 3464.5 | 38678 | 33291 |   | CN0 | 1,16181550569223
242 | 1509L0065-A_S10.recal.bam | chr3 | MLH1_ex14 | MLH1_ex14 | 37081626 | 37081805 | 3601 | 4151 | 33050 | 37762 |   | CN0 | 0,875218473597797
270 | 1509L0065-A_S10.recal.bam | chr3 | MITF_ex02 | MITF_ex02 | 69986922 | 69987220 | 5312 | 6270 | 48754 | 55663 |   | CN0 | 0,875878051847726
321 | 1509L0065-A_S10.recal.bam | chr5 | SDHA_ex13 | SDHA_ex13 | 251402 | 251603 | 2968 | 3275 | 24517 | 28350 |   | CN0 | 0,864797178130512

</body>

</html>

Thanks for your help,

Flora

**Comment by gpovysil** [comment]
Did you use the latest version on panelcn.mops from github (from November 2021)? This looks like the high (normalized) RC issue that should have been fixed in the latest version. If the issue is still there, please let me know and I will adapt the thresholds for extracting very high RCs.

**Comment by Fponelle** [comment]
Thanks for your really quick answer.

I'm actually using this version (bioconductor)

other attached packages:
[1] **panelcn.mops_1.16.0**  cn.mops_1.40.0       GenomicRanges_1.46.1
[4] GenomeInfoDb_1.30.1  IRanges_2.28.0       S4Vectors_0.32.3    
[7] BiocGenerics_0.40.0

**Comment by Fponelle** [comment]
I reinstalled panelcn.mops from github like described here:

> 
> install.packages("devtools")  
> devtools::install_github("bioinf-jku/panelcn.mops")  


I have less than with the bioconductor version but I still have problem on high normalized RC:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>

	
</head>

<body>


  | Sample | Chr | Gene | Exon | Start | End | RC | medRC | RC.norm | medRC.norm | lowQual | CN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
9 | 1509L0065-A_S10.recal.bam | chr1 | CHD5_ex35 | CHD5_ex35 | 6172179 | 6172387 | 4331 | 4953 | 39596 | 44704 |   | CN0
43 | 1509L0065-A_S10.recal.bam | chr1 | CHD5_ex01 | CHD5_ex01 | 6239984 | 6240133 | 3144 | 3077 | 34493 | 30300 |   | CN0
125 | 1509L0065-A_S10.recal.bam | chr1 | SDHC_ex06 | SDHC_ex06 | 161332068 | 161332243 | 3617 | 3582.5 | 39682 | 34122 |   | CN0
196 | 1509L0065-A_S10.recal.bam | chr2 | TMEM127_ex01 | TMEM127_ex01 | 96931119 | 96931250 | 3651 | 3634.5 | 40055 | 35866 |   | CN0
198 | 1509L0065-A_S10.recal.bam | chr2 | BCL2L11_UTR5_ex01 | BCL2L11_UTR5_ex01 | 111878490 | 111878765 | 3831 | 3464.5 | 38527 | 32991 |   | CN0
324 | 1509L0065-A_S10.recal.bam | chr5 | MSH3_UTR5 | MSH3_UTR5 | 79950470 | 79950546 | 2920 | 2998 | 32035 | 27509 |   | CN0
347 | 1509L0065-A_S10.recal.bam | chr5 | MSH3_ex23 | MSH3_ex23 | 80168884 | 80169126 | 4153 | 4787 | 37969 | 41082 |   | CN0
524 | 1509L0065-A_S10.recal.bam | chr8 | NBN_ex02 | NBN_ex02 | 90994929 | 90995133 | 3618 | 4350 | 39693 | 45609 |   | CN0
594 | 1509L0065-A_S10.recal.bam | chr11 | MEN1_ex04 | MEN1_ex04 | 64575003 | 64575202 | 3324 | 3442 | 36467 | 31124 |   | CN0
835 | 1509L0065-A_S10.recal.bam | chr14 | RAD51B_ex05 | RAD51B_ex05 | 68331669 | 68331876 | 3038 | 3712 | 33330 | 37816 |   | CN0


</body>

</html>

**Comment by gpovysil** [comment]
Sorry for the delay. I lowered the threshold for very high RCs to 25000 That should catch all of your exons. Can you please re-install from GitHub and try again?

**Comment by Fponelle** [comment]
I re-installed panelcn.MOPS from github but unfortunately I still have the problem

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>


<body>


  | Sample | Chr | Gene | Exon | Start | End | RC | medRC | RC.norm | medRC.norm | lowQual | CN |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
43 | 1509L0065-A_S10.recal.bam | chr1 | CHD5_ex01 | CHD5_ex01 | 6239984 | 6240133 | 3144 | 3077 | 32676 | 28181 |   | CN0 |  
67 | 1509L0065-A_S10.recal.bam | chr1 | MAP3K6_ex18 | MAP3K6_ex18 | 27685887 | 27686063 | 2830 | 3227.5 | 24510 | 28035 |   | CN0 |  
198 | 1509L0065-A_S10.recal.bam | chr2 | BCL2L11_UTR5_ex01 | BCL2L11_UTR5_ex01 | 111878490 | 111878765 | 3831 | 3464.5 | 39816 | 33083 |   | CN0 |  
295 | 1509L0065-A_S10.recal.bam | chr3 | CASR_ex06 | CASR_ex06 | 122000909 | 122001103 | 2756 | 3119.5 | 23870 | 27670 |   | CN0 |  
301 | 1509L0065-A_S10.recal.bam | chr4 | FAM175A_ex06 | FAM175A_ex06 | 84390164 | 84390354 | 2782 | 3066 | 24095 | 28486 |   | CN0 |  
320 | 1509L0065-A_S10.recal.bam | chr5 | SDHA_ex12 | SDHA_ex12 | 251056 | 251238 | 3145 | 3633.5 | 27239 | 33296 |   | CN0 |  
342 | 1509L0065-A_S10.recal.bam | chr5 | MSH3_ex18 | MSH3_ex18 | 80083333 | 80083511 | 2514 | 2952.5 | 21774 | 27126 |   | CN0 |  
354 | 1509L0065-A_S10.recal.bam | chr5 | APC_UTR5_ex04 | APC_UTR5_ex04 | 112090569 | 112090587 | 2374 | 2824.5 | 22617 | 27105 |   | CN0 |  
525 | 1509L0065-A_S10.recal.bam | chr8 | NBN_ex01 | NBN_ex01 | 90996732 | 90996839 | 2687 | 3247.5 | 23272 | 28282 |   | CN0 |  
526 | 1509L0065-A_S10.recal.bam | chr8 | NBN_UTR5 | NBN_UTR5 | 90996789 | 90996899 | 2646 | 3226.5 | 22917 | 27396 |   | CN0 |  
870 | 1509L0065-A_S10.recal.bam | chr14 | DICER1_UTR5_ex02 | DICER1_UTR5_ex02 | 95599795 | 95599840 | 2118 | 2563.5 | 20178 | 24096 |   | CN0 |  
1082 | 1509L0065-A_S10.recal.bam | chr17 | BRCA1_ex09 | BRCA1_ex09 | 41247842 | 41247989 | 2642 | 3275.5 | 27459 | 31208 |   | CN0 |  


</body>

</html>

**Comment by gpovysil** [comment]
Can you please share the messages that panelcn.mops generates?

**Comment by gpovysil** [comment]
I just noticed what the problem is. The high RC correction is applied before normalization since we never had the problem that the RCs were only extremely high after normalization, but not before. I will work on a fix, but it might take a while. Are you using standard parameters for normalization?

**Comment by Fponelle** [comment]
My output file is here:
[runcnMOPSOutput.txt](https://github.com/bioinf-jku/panelcn.mops/files/8151690/runcnMOPSOutput.txt)


My code is below:

> `## Creation reference à partir des autres échantillons du run 
> countWindows <- getWindows(bed, chr=TRUE)
> countWindows$exon = countWindows$name
> bams_ref = read.table(bam_list,header=F)$V1
> bams_ref=as.character(bams_ref)
> bams_ref=as.vector(bams_ref)
> 
> ref <- countBamListInGRanges(countWindows = countWindows, bam.files = bams_ref, read.width = 150)
> save(ref,file=paste(output_folder,"current_ref.rda",sep=""))
> 
> 
> 
> test = ref
> 
> XandCB <- test
> elementMetadata(XandCB) <- cbind(elementMetadata(XandCB),elementMetadata(ref))
> resultlist <- runPanelcnMops(XandCB,
> I = c(0.025,0.57,1,1.46,2),
> testiv = 1:ncol(elementMetadata(test)),
> countWindows = countWindows)
> 
> 
> sampleNames <- colnames(elementMetadata(test))
> 
> resulttable <- createResultTable(resultlist = resultlist, XandCB = XandCB,
> countWindows = countWindows,
> sampleNames = sampleNames)
> `

**Comment by gpovysil** [comment]
Very interesting. The problem seems to be that almost every other exon qualifies as a high coverage exon before normalization and is scaled down. As a result, the RCs of the remaining exons get scaled up during normalization.
I am preparing for a trip, so I am not sure how fast I can fix this. For now, you could just try to split up bigger exons using the function splitROIs and create a new bed file that you use as input for the read counting. That should also give you better resolution.

**Comment by gpovysil** [comment]
I implemented a quick fix, but don't have time to test it. If you want to try, just re-install from GitHub.

**Comment by Fponelle** [comment]
I have an error now 
> 
```
Normalizing...
Erreur dans h(simpleError(msg, call)) : 
  erreur d'ï¿½valuation de l'argument 'x' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'ncol' : objet 'XandCBMatrix' introuvable
Appels : runPanelcnMops -> panelcn.mops -> ncol -> .handleSimpleError -> h
Exécution arrêtée
```
There is no emergency, you can prepare your trip and we will discuss it later.

**Comment by gpovysil** [comment]
Should be fixed now.

**Comment by Fponelle** [comment]
Sorry for the delay. 
I still have problem with the new version.

I re-analysed an analysis for which I had good results with the version of panelcn.mops available on bioconductor, results are available [here](https://github.com/bioinf-jku/panelcn.mops/files/8159638/Run_22-003_panelcn.mops_bioconductor_release.zip) for bioconductor version and [here](https://github.com/bioinf-jku/panelcn.mops/files/8159642/Run_22-003_panelcn.mops_last_release.zip) with the last fix  you implemented

With the bioconductor version panelcn.mops finds the expected CNVs and some false positives but in very reasonable quantities.
The new fix seems to improve the problem on high RC and CN0 but it creates a lot of "lowqual" CNV and false positive deletion.

Don't hesitate if you need more informations on my data .

**Comment by Fponelle** [comment]
Hi,
Have you had time to think about my problem?
Thanks

**Comment by gpovysil** [comment]
Sorry for the delay. I will try to change back to the original version and include a warning if there are some extreme values. 
I looked at your RCs and they are all extremely high (overall minimum is above 300, minimum of median is almost 700). 
I think it's best if you use the splitROIs function and create a new bed file with larger exons split into smaller overlapping regions. That way you do not run into numerical problems and it should also make it possible to detect CNVs that only affect part of an exon.
